pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                bat 'dir'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t edulearn4 .'
            }
        }

        stage('Run Container') {
            steps {
                bat '''
                docker stop edulearn4 >nul 2>&1
                docker rm edulearn4 >nul 2>&1
                docker run -d -p 8081:80 --name edulearn4 edulearn4
                '''
            }
        }
    }
}