pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                bat 'dir'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'cd EduLearn && docker build -t edulearn .'
            }
        }

        stage('Run Container') {
            steps {
                bat '''
                docker stop edulearn >nul 2>&1
                docker rm edulearn >nul 2>&1
                docker run -d -p 8081:80 --name edulearn edulearn
                '''
            }
        }
    }
}